version: "3"

services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - "8080:80"
      - "8070:8070"
  nodeserver1:
    build:
      context: .
    container_name: node-continer1
    volumes:
      - ./src:/app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
  nodeserver2:
    build:
      context: .
    container_name: node-continer2
    volumes:
      - ./src:/app
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
